### PR TITLE
Graphs should be bucketed per day

### PR DESCRIPTION
**Pull request by mutatrum**
This fixes several issues with the bucketing in graphs and simplifies the date/time math:
- Buckets per day or hour are stable, as they are bucketed per whole hour/day;
- First buckets don't slowly drain. due to passing of time on the current day;
- Fixed timezone issues, slicing a ISO date loses the timezone information;
- Formatting of hour bars added.

### CODE REVIEW

**Comment by mutatrum** [comment]
This has some overlap with https://github.com/apotdevin/thunderhub/pull/415, which I only saw when I was close to finished.

**Comment by mutatrum** [comment]
I verified the numbers per bar against my node using

```lncli fwdinghistory --start_time 1646485200 --end_time 1646488800 --max_events 1000000 | jq ".forwarding_events | length"```

with start and time times taken from https://www.unixtimestamp.com/.

I'm on UTC+1, it would be good if someone on the other side of the dateline can verify this as well.

**Comment by apotdevin** [comment]
Hey! Considering that this is very similar to https://github.com/apotdevin/thunderhub/pull/415 that was created a while back, I'll take priority on that one

**Comment by mutatrum** [comment]
There are some issues with that implementation, mainly regarding timezones.

**Comment by apotdevin** [comment]
Ah I see the issue now! I'll merge this in

**Pull request merged**
