### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by krtk6160**

### CODE REVIEW

**Comment by apotdevin** [comment]
Awesome! Thanks for the note. What do you think about specifying `gRPC` instead of `RPC`?

**Comment by krtk6160** [comment]
There's an inconsistency in LND where starting lnd with the default config, in the logs it says:
- for port 8080: `gRPC proxy started at 0.0.0.0:8080`

whereas for
- port 10009 it says: `Password RPC server listening on 0.0.0.0:10009`

However, the [sample-lnd.conf](https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L137) mentions 10009 as gRPC.

Not sure about the difference between the two.

**Comment by apotdevin** [comment]
Let's better specify that it's the `gRPC` port since in a lot of documentation this is whats mentioned. If you can do this small change and I'll get it merged in asap!

**Comment by krtk6160** [comment]
> Let's better specify that it's the `gRPC` port since in a lot of documentation this is whats mentioned. If you can do this small change and I'll get it merged in asap!

Done

**Pull request merged**
